server:
  host: "0.0.0.0"
  port: "8080"

hosts:
  - name: "backend"
    enabled: true
    templates:
      new_user: "New user registered: {{.username}} (Total users: {{.total_users}})"
      user_login: "User login: {{.username}}"
      error: "Backend error: {{.error}}"
      default: "Backend: {{.message}}"
    
  - name: "status-checker"
    enabled: true
    templates:
      service_down: "Service {{.service_name}} is down!"
      service_up: "Service {{.service_name}} is back up!"
      default: "Status Checker: {{.message}}"